### ISSUE TITLE
Pscheduler does not display the summer and fall 2019 timetables (only spring 2019)

### ISSUE THREAD

**Issue by ervinkellym** [PhillipNgo/PScheduler#22]

**Comment by PhillipNgo** [comment]
Thanks for the report! Right now, the process for adding a new semester is manual. I'll be doing that tonight if it all goes smoothly, also the site doesn't support summer/winter semesters right now.

I'll close this when the update is out!

**Comment by PhillipNgo** [comment]
I've added the Fall 2019 courses! Let me know if there any problems

**Comment by ervinkellym** [comment]
It looks great, thanks a bunch!
