### ISSUE TITLE
Schedule Limit

### ISSUE THREAD

**Issue by PhillipNgo** [PhillipNgo/PScheduler#7]
Currently the schedule limit is 100 to avoid long periods of generation in case there are thousands of schedules. There are also tons of duplicate schedules that look the same but might have different CRNs/instructors. Change how schedule generation works so that it will only display different time configurations rather than every possible schedule. Each configuration would look very similar to a builder schedule in that it will have a CRN dropdown if there are multiple classes with the same time but different CRN/instructor.

**Comment by PhillipNgo** [comment]
This change won't work in conjunction with #4. Maybe it could be a toggle that can't be selected at the same time as Grades.

**Comment by sakgoyal** [comment]
any update on when this will happen?

**Comment by PhillipNgo** [comment]
This is already out

**Comment by sakgoyal** [comment]
When I use it, i get 1000 results and most of them are duplicates (same schedule but different CRN).

**Comment by PhillipNgo** [comment]
Once you reach 1000 a button appears in the top right allowing you to load up to 1000 more at a time. This happens a lot of w/ courses that have a ton of online classes, I would suggest taking out the class with a ton of online options or just choosing a single crn if you plan on doing online

**Comment by sakgoyal** [comment]
I have not selected any online courses.
