### ISSUE TITLE
API Errors?

### ISSUE THREAD

**Issue by HackintoshMan** [PhillipNgo/PScheduler#9]
Hey just checked this out on Safari 12.0 and there are some errors connecting to your API:
```
[Error] Origin https://www.pscheduler.com is not allowed by Access-Control-Allow-Origin.
[Error] Fetch API cannot load https://fdnvrxrba7.execute-api.us-east-1.amazonaws.com/beta/courses/search?query=CS%201114&size=1000&term=201809 due to access control checks.
[Error] Failed to load resource: Origin https://www.pscheduler.com is not allowed by Access-Control-Allow-Origin. (search, line 0)
```
I think this is because you are trying to load an Ajax resource outside of the www.pscheduler.com domain.

**Comment by PhillipNgo** [comment]
Were you able to send another request afterwards succesfully?

**Comment by HackintoshMan** [comment]
Yeah I was able to get search results when using [pscheduler.com](pscheduler.com).

**Comment by PhillipNgo** [comment]
Accessing `www.pscheduler.com` now redirects to `pscheduler.com`
